### ISSUE TITLE
Annotation Tool Improvement Checklist

### ISSUE THREAD

**Issue by zplizzi** [caltech-mars/issues#2]
A checklist of features requested for the annotation tool, to be completed by 11/7/16.

## TODO - David
- [ ] Record timing information
- [ ] Shortcut Keys
- [ ] Comments box

## TODO - Zack
- [ ] Link to slideshow of example annotations
- [ ] Update to newest set of keypoints and descriptions
- [ ] Distribute to team and each annotate 25 frames

### Timing information
Measure the time between clicks on the annotation tool, and record to database. 

### Shortcut keys
Add shortcut keys for the button options (submit, clear, back).

### Comments box
Add a box where users can optionally make comments about the annotation. Record to database
